api = "0.5"

[buildpack]
id = "google.php.composer"
version = "0.9.1"
name = "PHP - Composer"

[[stacks]]
id = "google"

[[stacks]]
id = "google.php72"

[[stacks]]
id = "google.php73"

[[stacks]]
id = "google.php74"

[[stacks]]
id = "google.php81"
