api = "0.8"

[buildpack]
id = "google.java.graalvm"
version = "0.1.0"
name = "Java - GraalVM"

# The cloud run source deploy command uses pack. Older versions of pack which
# were distributed by gcloud for cloud run do not support wildcard stack id
# matching. For that reason we must allow an explicit stack id of 'google'
[[stacks]]
id = "google"

[[stacks]]
id = "*"