api = "0.5"

[buildpack]
id = "google.php.functions-framework"
version = "0.9.5"
name = "Google - PHP - Functions Framework"

# The cloud run source deploy command uses pack. Older versions of pack which
# were distributed by gcloud for cloud run do not support wildcard stack id
# matching. For that reason we must allow an explicit stack id of 'google'
[[stacks]]
id = "google"

[[stacks]]
id = "*"