api = "0.5"

[buildpack]
id = "google.python.webserver"
version = "0.9.1"
name = "Python - webserver"

[[stacks]]
id = "google.python37"

[[stacks]]
id = "google.python38"

[[stacks]]
id = "google.python39"
