description = "Builder for the GCF Java 11 runtime"

[[buildpacks]]
  id = "google.java.maven"
  uri = "maven.tgz"

[[buildpacks]]
  id = "google.java.functions-framework"
  uri = "functions_framework.tgz"

# We'll use google.java.maven to compile the function code if there is a pom.xml.
# In that case google.java.functions-framework will inspect the pom.xml to
# determine what should be in the classpath of the final function. Otherwise, it
# expects there is an already-compiled jar file and that's what it will put in
# the classpath.
[[order]]
  [[order.group]]
    id = "google.java.maven"
    optional = true

  [[order.group]]
    id = "google.java.functions-framework"

[stack]
  id = "google.java11"
  build-image = "gcr.io/gae-runtimes/buildpacks/java11/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/java11/run"

[lifecycle]
  version = "0.7.5"
