description = "Builder for the GCF Go 1.11 runtime"

[[buildpacks]]
  id = "google.go.build"
  uri = "build.tgz"

[[buildpacks]]
  id = "google.go.legacy-worker"
  uri = "legacy_worker.tgz"

[[buildpacks]]
  id = "google.utils.archive-source"
  uri = "archive_source.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]

  [[order.group]]
    id = "google.utils.archive-source"

  [[order.group]]
    id = "google.go.legacy-worker"

  [[order.group]]
    id = "google.go.build"

  [[order.group]]
    id = "google.utils.label"

[stack]
  id = "google.go111"
  build-image = "gcr.io/gae-runtimes/buildpacks/go111/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/go111/run"

[lifecycle]
  version = "0.11.1"
