api = "0.2"

[buildpack]
id = "google.python.functions-framework-compat"
version = "0.9.0"
name = "Python - Functions Framework (compatibility)"

[[stacks]]
id = "google"

[[stacks]]
id = "google.python37"
