api = "0.2"

[buildpack]
id = "google.nodejs.npm"
version = "0.9.0"
name = "Node.js - NPM"

[[stacks]]
id = "google"

[[stacks]]
id = "google.nodejs10"

[[stacks]]
id = "google.nodejs12"

[[stacks]]
id = "google.nodejs14"