description = "Builder for the Java runtime"

[[buildpacks]]
  id = "google.buildpackages.java"
  uri = "buildpackage.cnb"

[[order]]
  [[order.group]]
    id = "google.buildpackages.java"

# Currently built with //builders/gcp/base/stack/stack:build.
[stack]
  id = "google.gae.18"
  build-image = "gcr.io/gae-runtimes/buildpacks/stacks/google-gae-18/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/stacks/google-gae-18/run"

[lifecycle]
  version = "0.16.0"
