description = "Unified builder for the Go runtime"

[[buildpacks]]
  id = "google.go"
  uri = "go.cnb"

[[order]]
  [[order.group]]
    id = "google.go"

[stack]
  id = "google.gae.18"
  build-image = "gcr.io/gae-runtimes/buildpacks/stacks/google-gae-18/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/stacks/google-gae-18/run"

[lifecycle]
  version = "0.13.3"