description = "Unified builder for the Go runtime"

[[buildpacks]]
  id = "google.config.entrypoint"
  uri = "entrypoint.tgz"

[[buildpacks]]
  id = "google.go.clear_source"
  uri = "clear_source.tgz"

[[buildpacks]]
  id = "google.go.runtime"
  uri = "runtime.tgz"

[[buildpacks]]
  id = "google.go.gomod"
  uri = "gomod.tgz"

[[buildpacks]]
  id = "google.go.build"
  uri = "build.tgz"

[[buildpacks]]
  id = "google.go.gopath"
  uri = "gopath.tgz"

[[buildpacks]]
  id = "google.go.functions-framework"
  uri = "functions_framework.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]

  [[order.group]]
    id = "google.go.runtime"

  [[order.group]]
    id = "google.go.functions-framework"

  [[order.group]]
    id = "google.go.build"

  [[order.group]]
    id = "google.config.entrypoint"
    optional = true

  [[order.group]]
    id = "google.go.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

[[order]]

  [[order.group]]
    id = "google.go.runtime"

  [[order.group]]
    id = "google.go.gomod"

  [[order.group]]
    id = "google.go.build"

  [[order.group]]
    id = "google.config.entrypoint"
    optional = true

  [[order.group]]
    id = "google.go.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

[[order]]

  [[order.group]]
    id = "google.go.runtime"

  [[order.group]]
    id = "google.go.gopath"
    optional = true

  [[order.group]]
    id = "google.go.build"

  [[order.group]]
    id = "google.config.entrypoint"
    optional = true

  [[order.group]]
    id = "google.go.clear_source"
    optional = true

  [[order.group]]
    id = "google.utils.label"

# Currently built with //builders/gcp/base/stack/stack:build.
[stack]
  id = "google"
  build-image = "gcr.io/buildpacks/gcp/build:v1"
  run-image = "gcr.io/buildpacks/gcp/run:v1"

[lifecycle]
  version = "0.13.3"