api = "0.6"

[buildpack]
id = "google.utils.label"
version = "0.0.2"
name = "Utils - Label Image"
homepage = "https://github.com/GoogleCloudPlatform/buildpacks/tree/main/cmd/utils/label"

[[stacks]]
id = "google"

[[stacks]]
id = "*"