api = "0.2"

[buildpack]
id = "google.nodejs.yarn"
version = "0.9.0"
name = "Node.js - Yarn"

[[stacks]]
id = "google"

[[stacks]]
id = "google.nodejs10"

[[stacks]]
id = "google.nodejs12"

[[stacks]]
id = "google.nodejs14"