description = "Unified builder for the .NET runtime"

[stack]
  id = "google"
  build-image = "gcr.io/buildpacks/gcp/build:v1"
  run-image = "gcr.io/buildpacks/gcp/run:v1"

[lifecycle]
  version = "0.13.3"