api = "0.5"

[buildpack]
id = "google.ruby.bundle"
version = "0.9.0"
name = "Ruby - Bundle"

[[stacks]]
id = "google"

[[stacks]]
id = "google.ruby25"

[[stacks]]
id = "google.ruby26"

[[stacks]]
id = "google.ruby27"

[[stacks]]
id = "google.ruby30"
