api = "0.6"

[buildpack]
  id = "google.dotnet"
  version = "0.1.0"
  name = ".NET"

[metadata]
  include-files = ["buildpack.toml"]

# AppEngine order group
[[order]]

  [[order.group]]
    id = "google.dotnet.sdk"
    version = "0.9.1"

  [[order.group]]
    id = "google.dotnet.appengine_main"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "google.dotnet.publish"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "google.dotnet.runtime"
    version = "0.9.1"

  [[order.group]]
    id = "google.dotnet.appengine"
    version = "0.9.0"

  [[order.group]]
    id = "google.utils.label"
    version = "0.0.2"

# GCF order group
[[order]]

  [[order.group]]
    id = "google.dotnet.sdk"
    version = "0.9.1"

  [[order.group]]
    id = "google.utils.archive-source"
    version = "0.0.1"

  [[order.group]]
    id = "google.dotnet.functions-framework"
    version = "0.0.1"

  [[order.group]]
    id = "google.dotnet.publish"
    version = "0.9.0"

  [[order.group]]
    id = "google.dotnet.runtime"
    version = "0.9.1"

  [[order.group]]
    id = "google.utils.label"
    version = "0.0.2"

# Cloud Run / General purpose order group
[[order]]

  [[order.group]]
    id = "google.dotnet.sdk"
    version = "0.9.1"

  [[order.group]]
    id = "google.dotnet.functions-framework"
    version = "0.0.1"
    optional = true

  [[order.group]]
    id = "google.dotnet.publish"
    version = "0.9.0"

  [[order.group]]
    id = "google.dotnet.runtime"
    version = "0.9.1"

  [[order.group]]
    id = "google.config.entrypoint"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "google.utils.label"
    version = "0.0.2"

# Prebuilt .NET applications.
[[order]]

  [[order.group]]
    id = "google.dotnet.runtime"
    version = "0.9.1"

  [[order.group]]
    id = "google.config.entrypoint"
    version = "0.9.0"

  [[order.group]]
    id = "google.utils.label"
    version = "0.0.2"

[lifecycle]
  version = "0.13.3"