description = "Builder for the GAE PHP 8.1 runtime"

[[buildpacks]]
  id = "google.php.composer"
  uri = "composer.tgz"

[[buildpacks]]
  id = "google.php.composer-gcp-build"
  uri = "composer_gcp_build.tgz"

[[buildpacks]]
  id = "google.php.composer-install"
  uri = "composer_install.tgz"

[[buildpacks]]
  id = "google.php.appengine"
  uri = "appengine.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]
  [[order.group]]
    id = "google.php.composer-install"
    optional = true

  [[order.group]]
    id = "google.php.composer-gcp-build"
    optional = true

  [[order.group]]
    id = "google.php.composer"
    optional = true

  [[order.group]]
    id = "google.php.appengine"

  [[order.group]]
    id = "google.utils.label"

[stack]
  id = "google.php81"
  build-image = "gcr.io/gae-runtimes/buildpacks/php81/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/php81/run"

[lifecycle]
  version = "0.13.3"
