api = "0.2"

[buildpack]
id = "google.go.gomod"
version = "0.9.0"
name = "Go - Gomod"

[[stacks]]
id = "google.go111"

[[stacks]]
id = "google.go112"

[[stacks]]
id = "google.go113"

[[stacks]]
id = "google.go114"
