api = "0.5"

[buildpack]
id = "google.java.functions-framework"
version = "1.1.0"
name = "Java - Functions Framework Invoker"

[[stacks]]
id = "google"

[[stacks]]
id = "google.java11"

[[stacks]]
id = "google.java17"
